import React from 'react'

const About = () => {
  return (
    <div>
      I am about
    </div>
  )
}

export default About

export const metadata = {
  title: "About | YouTube",
  description: "Generated by create next app",
};