export const metadata = {
    title: "Admin Pages | Facebook",
    description: "Generated by create next app - Admin Pages",
};

export default function AdminLayout({ children }) {
    return (
        <>
            <div>Admin Navbar</div>
            {children}
        </>
    );
}
