export const metadata = {
    title: "Logout | Facebook",
    description: "Generated by create next app - Logout",
};

export default function LogoutLayout({ children }) {
    return (
        <>
            <div>Logout Navbar</div>
            {children}
        </>
    );
}
