import React from 'react'
import Script from 'next/script'
import Image from 'next/image'

const Contact = () => {
    return (
        <div>
            <Script>
                {`alert('Welcome to Contact page');`}
            </Script>

            I am contact

            <div>
                <Image width={200} height={200} src="https://img.freepik.com/free-vector/error-404-concept-landing-page_52683-10996.jpg?ga=GA1.1.540240835.1738300642&semt=ais_hybrid&w=740" alt="" />
            </div>
        </div>
    )
}

export default Contact

export const metadata = {
    title: "Contact | YouTube",
    description: "Generated by create next app",
};